import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from run import run
from run import load_file_from_disk
from common.pymilvus_connection import PymilvusConnection


if __name__ == '__main__':
    # 1. pid_list contains all the pid which you want to recall similar papers.
    pid_list = [526810, 526809, 526805, 526814, 526779, 526760, 526746]
    # 2. get the mapping dict generated by pub.json.
    # format {pid: obj, }
    pub_json_obj = load_file_from_disk()
    # 3. connect to milvus&return the target collection
    milvus = PymilvusConnection()
    conn = milvus.get_embedding_collection()
    # 4. for each pid and recall similar papers.
    for pid in pid_list:
        print(run(pid, pub_json_obj, conn))
    # Attention: remember to release the collection which has loaded in memory.
    conn.release()
